CREATE DATABASE PROJETO;

/*CONECTANDO AO BANCO*/

USE PROJETO;

/*CRIANDO A TABELA DE CLIENTES*/

CREATE TABLE CLIENTES(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)

);

/*VERIFICANDO AS TABELAS DO BANCO DE DADOS*/

SHOW TABLES;

/*DESCOBRINCO COMO É A ESTRUTURA DE UMA TABELA*/
DESC CLIENTE;

/*FORMA 01 - INSERIR DADOS*/
INSERT INTO CLIENTES VALUES ('Thalles', 'M', 'thallescerqueira.dev@gmail.com', 12345, "73991556511", "RUA NOVA");
INSERT INTO CLIENTES VALUES ('TAISY', 'F', 'TAISY@gmail.com', 98766, "73991556511", "RUA NOVA");
INSERT INTO CLIENTES VALUES ('IVONE', 'F', 'IVONE@gmail.com', 342342, "73991556511", "RUA NOVA");
INSERT INTO CLIENTES VALUES ('DAVI', 'M', 'DAVI@gmail.com', 1345543, "73991556511", "RUA NOVA");

/*COMANDO SELECT*/
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTES;

/*PROJETANDO TODOS OS DADOS DA TABELA*/
SELECT * FROM CLIENTES;

/*FAZENDO FILTROS*/
SELECT NOME, SEXO FROM CLIENTES
WHERE SEXO = 'M';

SELECT NOME, SEXO FROM CLIENTES WHERE SEXO = 'F';

/*CONTANDO TODOS OS REGISTROS DE UMA TABELA*/
SELECT COUNT(*) FROM CLIENTES;

/*OPERADOR GROUP BY*/
SELECT SEXO, COUNT(*)
FROM CLIENTES;

/* VERIFICANDO TOTAL POR SEXO */
SELECT SEXO, COUNT(*) AS TOTAL
FROM CLIENTES
GROUP BY SEXO;

/* ATUALIZANDO DADOS */
SELECT NOME, EMAIL FROM CLIENTES;

UPDATE CLIENTES
SET EMAIL = "updateEmailDavi@gmail.com"
WHERE NOME = 'DAVI';

/* DELETANDO DADOS */
DELETE FROM CLIENTES WHERE NOME = 'Thalles';