UPDATE [TABELA DE PRODUTOS]
SET PRECO_LISTA = PRECO_LISTA * 0.90
WHERE EMBALAGEM = 'Lata';

SELECT * FROM [TABELA DE PRODUTOS];

UPDATE [TABELA DE PRODUTOS]
SET EMBALAGEM = 'Garrafa', PRECO_LISTA = 8.10
WHERE CODIGO_PRODUTO = '104111';

DELETE FROM [TABELA DE PRODUTOS]
WHERE CODIGO_PRODUTO = '1040108'