SELECT * FROM [TABELA DE PRODUTOS];

SELECT * FROM [TABELA DE CLIENTES];

SELECT NOME, ESTADO FROM [TABELA DE CLIENTES];

SELECT NOME, ESTADO FROM [TABELA DE CLIENTES] ORDER BY NOME ASC;

/* AULA 5 */
SELECT NOME AS [Nome do Cliente], CPF, ESTADO AS UF FROM [TABELA DE CLIENTES];

SELECT MATRICULA AS Identificador, NOME AS [Nome do Vendedor] FROM [TABELA DE VENDEDORES];

SELECT DISTINCT SABOR FROM [TABELA DE PRODUTOS];

SELECT NOME, ESTADO AS UF, PRIMEIRA_COMPRA 
FROM [TABELA DE CLIENTES] 
WHERE PRIMEIRA_COMPRA = 1;

SELECT * FROM [TABELA DE PRODUTOS] WHERE PRECO_LISTA >= 7.00;

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM > 'Lata';

SELECT NOME, DATA_NASCIMENTO FROM [TABELA DE CLIENTES] WHERE DATA_NASCIMENTO > '1995-01-01';

SELECT NOME, DATA_NASCIMENTO FROM [TABELA DE CLIENTES] WHERE YEAR(DATA_NASCIMENTO) > '1995';

SELECT NOME, BAIRRO FROM [TABELA DE CLIENTES] WHERE BAIRRO = 'Copacabana' OR BAIRRO = 'Tijuca';

SELECT NOME, ESTADO, PRIMEIRA_COMPRA FROM [TABELA DE CLIENTES] WHERE PRIMEIRA_COMPRA = 1 AND ESTADO = 'SP';

SELECT NOME, PERCENTUAL_COMISSAO FROM [TABELA DE VENDEDORES] WHERE PERCENTUAL_COMISSAO <= 8;

SELECT NOME, PRECO_LISTA, EMBALAGEM FROM [TABELA DE PRODUTOS] WHERE PRECO_LISTA <= 7 AND EMBALAGEM = 'Lata';

SELECT * FROM [TABELA DE PRODUTOS];

SELECT * FROM [TABELA DE CLIENTES] WHERE ESTADO <> 'SP' AND ESTADO <> 'RJ';