CREATE TABLE [TABELA DE CLIENTES] (
	CPF CHAR(11),
	NOME VARCHAR(130),
	RUA VARCHAR(130),
	COMPLEMENTO VARCHAR(130),
	BAIRRO VARCHAR(130),
	ESTADO CHAR(2),
	CEP CHAR(8),
	DATA_NASCIMENTO DATE,
	IDADE SMALLINT,
	SEXO CHAR(1),
	LIMITE_CREDITO MONEY,
	VOLUME_MINIMO FLOAT,
	PRIMEIRA_COMPRA BIT

);

CREATE TABLE [TABELA DE PRODUTOS](

	CODIGO_PRODUTO VARCHAR(20) NOT NULL PRIMARY KEY,
	NOME VARCHAR(50),
	EMBALAGEM VARCHAR(50),
	TAMANHO VARCHAR(50),
	SABOR VARCHAR(50),
	PRECO_LISTA SMALLMONEY

);

CREATE TABLE [TABELA DE VENDEDORES] (

	MATRICULA VARCHAR(5) NOT NULL PRIMARY KEY,
	NOME VARCHAR(100),
	PERCENTUAL_COMISSAO FLOAT

);

ALTER TABLE [TABELA DE CLIENTES] ALTER COLUMN CPF CHAR(11) NOT NULL;
ALTER TABLE [TABELA DE CLIENTES] ADD CONSTRAINT PK_TABELA_CLIENTE PRIMARY KEY CLUSTERED (CPF);
