SELECT PRODUTOS.EMBALAGEM, AVG(PRODUTOS.PRECO_DE_LISTA) AS [PRECO MEDIO]
FROM TABELA_DE_PRODUTOS PRODUTOS
GROUP BY PRODUTOS.EMBALAGEM
HAVING AVG(PRODUTOS.PRECO_DE_LISTA) <= 10;

SELECT MEDIA.EMBALAGEM,
MEDIA.[PRECO MEDIO]
FROM
(SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS [PRECO MEDIO]
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM) MEDIA
WHERE [PRECO MEDIO] <= 10;


SELECT MEDIA.CODIGO_DO_PRODUTO, MEDIA.NOME_DO_PRODUTO, MEDIA.QUANTIDADE
FROM
(SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO) MEDIA
WHERE MEDIA.QUANTIDADE > 394000
ORDER BY MEDIA.QUANTIDADE DESC