SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
-- 12 BAIRROS RELACIONADOS COM CLIENTES

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES



SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES


SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES