SELECT CONVERT(VARCHAR(30), GETDATE(), 121)

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(25), DATA_DE_NASCIMENTO, 121) AS DATA_FORMATADA FROM TABELA_DE_CLIENTES


SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(25), DATA_DE_NASCIMENTO, 106) AS DATA_FORMATADA FROM TABELA_DE_CLIENTES


SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA from TABELA_DE_PRODUTOS

SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é ', PRECO_DE_LISTA) as preco from TABELA_DE_PRODUTOS

SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é ', CAST(PRECO_DE_LISTA AS varchar(10))) as preco from TABELA_DE_PRODUTOS
