SELECT VENDEDORES.BAIRRO, VENDEDORES.NOME
FROM TABELA_DE_VENDEDORES VENDEDORES
WHERE VENDEDORES.BAIRRO IS NOT NULL

SELECT CLIENTES.NOME, CLIENTES.BAIRRO FROM TABELA_DE_CLIENTES CLIENTES
WHERE BAIRRO IN 
(
SELECT VENDEDORES.BAIRRO
FROM TABELA_DE_VENDEDORES VENDEDORES
WHERE VENDEDORES.BAIRRO IS NOT NULL
)


SELECT PRODUTOS.NOME_DO_PRODUTO AS [PRODUTOS MAIS VENDIDOS]
FROM TABELA_DE_PRODUTOS PRODUTOS
WHERE PRODUTOS.CODIGO_DO_PRODUTO IN 
(
SELECT 
INF.CODIGO_DO_PRODUTO
FROM 
ITENS_NOTAS_FISCAIS  INF
INNER JOIN 
TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY 
INF.CODIGO_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
)