SELECT DISTINCT CIDADE, ESTADO FROM TABELA_DE_CLIENTES;

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Maca'

SELECT DISTINCT EMBALAGEM, SABOR FROM TABELA_DE_PRODUTOS

SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS;