CREATE VIEW MEDIA_EMBALAGEM AS
SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS [PRECO MEDIO]
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM

CREATE VIEW MEDIA AS
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO

SELECT * FROM MEDIA_EMBALAGEM

SELECT EMBALAGEM, [PRECO MEDIO]
FROM MEDIA_EMBALAGEM
WHERE [PRECO MEDIO] <= 10


SELECT MEDIA.CODIGO_DO_PRODUTO, MEDIA.NOME_DO_PRODUTO, MEDIA.QUANTIDADE
FROM MEDIA
WHERE MEDIA.QUANTIDADE > 394000
ORDER BY MEDIA.QUANTIDADE DESC