SELECT ROUND(3.4362, 3) AS ROUND_,
CEILING(3.4362) AS CEILING_,
FLOOR(3.4362) AS FLOOR_,
POWER(3.4362, 12) AS POWER_,
EXP(3) AS EXP_,
SQRT(144) AS SQRT_,
ABS(-10) AS ABS_

SELECT * FROM NOTAS_FISCAIS N;

SELECT * FROM ITENS_NOTAS_FISCAIS

SELECT YEAR(DATA_VENDA) AS ANO, FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) 
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA);