SELECT * FROM TABELA_DE_VENDEDORES

SELECT * FROM NOTAS_FISCAIS

SELECT V.NOME, V.MATRICULA, N.DATA_VENDA, N.NUMERO
FROM TABELA_DE_VENDEDORES V
INNER JOIN NOTAS_FISCAIS N ON
V.MATRICULA = N.MATRICULA

SELECT N.MATRICULA, V.NOME, COUNT(*) AS NUMERO_NOTAS 
FROM NOTAS_FISCAIS N
INNER JOIN TABELA_DE_VENDEDORES V
ON N.MATRICULA = V.MATRICULA
GROUP BY N.MATRICULA, NOME;

SELECT N.CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS N
INNER JOIN TABELA_DE_PRODUTOS P
ON N.CODIGO_DO_PRODUTO = P.CODIGO_DO_PRODUTO
GROUP BY N.CODIGO_DO_PRODUTO, NOME_DO_PRODUTO HAVING SUM(QUANTIDADE) > 394000 
ORDER BY SUM(QUANTIDADE) DESC;