SELECT CONVERT(VARCHAR(30), GETDATE(), 121)

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(25), DATA_DE_NASCIMENTO, 121) AS DATA_FORMATADA FROM TABELA_DE_CLIENTES


SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(25), DATA_DE_NASCIMENTO, 106) AS DATA_FORMATADA FROM TABELA_DE_CLIENTES


SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA from TABELA_DE_PRODUTOS

SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é ', PRECO_DE_LISTA) as preco from TABELA_DE_PRODUTOS

SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é ', CAST(PRECO_DE_LISTA AS varchar(10))) as preco from TABELA_DE_PRODUTOS


SELECT TC.NOME, CONCAT('O cliente ', TC.NOME, ' comprou R$ ',
TRIM(STR(SUM(IT.QUANTIDADE * IT.PRECO) ,10,2)), ' no ano de ', YEAR(NF.DATA_VENDA), '.') AS VALOR
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS IT ON NF.NUMERO = IT.NUMERO
INNER JOIN TABELA_DE_CLIENTES AS TC ON NF.CPF = TC.CPF
WHERE YEAR(NF.DATA_VENDA) = '2016'
GROUP BY TC.NOME, YEAR(NF.DATA_VENDA);
