CREATE VIEW MEDIA_EMBALAGEM AS
SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS [PRECO MEDIO]
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM

SELECT * FROM MEDIA_EMBALAGEM

SELECT EMBALAGEM, [PRECO MEDIO]
FROM MEDIA_EMBALAGEM
WHERE [PRECO MEDIO] <= 10
