SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('LIMA/LIMaO', 'Morango/Limao' );

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Limao'

SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%MACA%';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE 'Morango%';

SELECT * FROM TABELA_DE_PRODUTOS WHERE (SABOR LIKE 'Morango%') AND TAMANHO = '700 ml' ;