SELECT * FROM TABELA_DE_CLIENTES

SELECT * FROM TABELA_DE_CLIENTES WHERE 1=1;

SELECT * FROM TABELA_DE_PRODUTOS

SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO = '1000889'

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja'

SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'PET'