SELECT GETDATE()

SELECT DATEADD(DAY, 10, GETDATE()) AS DATA;

SELECT DATEADD(DAY, -10, GETDATE()) AS DIAS_ATRAS;

SELECT 
CONCAT(
CLIENTE.NOME,
', ',
DATENAME(DAY, CLIENTE.DATA_DE_NASCIMENTO),
' de ',
DATENAME(MONTH, CLIENTE.DATA_DE_NASCIMENTO),
' de ',
DATENAME(YEAR, CLIENTE.DATA_DE_NASCIMENTO)
) 
AS NOME_DATA
FROM TABELA_DE_CLIENTES AS CLIENTE