SELECT * FROM TABELA_DE_CLIENTES

SELECT CPF, NOME, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES

SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DO CLIENTE], BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DO CLIENTE], BAIRRO, CIDADE FROM TABELA_DE_CLIENTES TDC;

SELECT TDC.* FROM TABELA_DE_CLIENTES TDC;

SELECT TABELA_DE_CLIENTES.CPF FROM TABELA_DE_CLIENTES;

