SELECT * FROM TABELA_DE_PRODUTOS

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MANGA' and TAMANHO = '470 ml';

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT  (SABOR = 'MANGA' and TAMANHO = '470 ml');

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR SABOR = 'Laranja' OR SABOR = 'MELANCIA';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR in ('Manga','Laranja', 'MELANCIA') and tamanho = '1 Litro';

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de janeiro', 'Sao Paulo')

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de janeiro', 'Sao Paulo') and idade >= 20;

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de janeiro', 'Sao Paulo') and idade >= 20 and idade <= 25;

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de janeiro', 'Sao Paulo') and (IDADE BETWEEN 20 AND 25);