SELECT 
N.CPF,
CONVERT(VARCHAR(7), N.DATA_VENDA) AS DATA, 
SUM(I.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS N
INNER JOIN ITENS_NOTAS_FISCAIS I
ON N.NUMERO = I.NUMERO
GROUP BY 
N.CPF,
CONVERT(VARCHAR(7), N.DATA_VENDA)

CREATE VIEW QUERY_INICIAL
AS
SELECT 
N.CPF,
CONVERT(VARCHAR(7), N.DATA_VENDA) AS DATA, 
SUM(I.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS N
INNER JOIN ITENS_NOTAS_FISCAIS I
ON N.NUMERO = I.NUMERO
GROUP BY 
N.CPF,
CONVERT(VARCHAR(7), N.DATA_VENDA)


SELECT CPF, NOME, VOLUME_DE_COMPRA
FROM TABELA_DE_CLIENTES

CREATE VIEW FILTRO
AS
SELECT 
C.CPF as Cpf, 
C.NOME as Nome, 
Q.DATA as Data, 
C.VOLUME_DE_COMPRA AS Volume, 
Q.QUANTIDADE_TOTAL AS [Quantidade Total],
(CASE WHEN C.VOLUME_DE_COMPRA >= Q.QUANTIDADE_TOTAL THEN 'Vendas válidas' ELSE 'Vendas Inválidas' END) AS Resultado
FROM TABELA_DE_CLIENTES C
INNER JOIN QUERY_INICIAL Q
ON C.CPF = Q.CPF
WHERE Q.DATA = '2015-01'

SELECT *, ROUND((1 - (F.Volume/F.[Quantidade Total])) * 100, 2) AS Diferenca
FROM FILTRO F
WHERE F.Volume < F.[Quantidade Total]



-- NOVO DESAFIO 24.10
CREATE VIEW VENDAS_POR_SABOR AS
SELECT 
P.SABOR, 
YEAR(N.DATA_VENDA) AS [Ano], 
SUM(I.QUANTIDADE) AS [Venda por Ano]
FROM TABELA_DE_PRODUTOS P
INNER JOIN ITENS_NOTAS_FISCAIS I
ON P.CODIGO_DO_PRODUTO = I.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS N
ON I.NUMERO = N.NUMERO
WHERE YEAR(N.DATA_VENDA) = 2015
GROUP BY P.SABOR, YEAR(N.DATA_VENDA)

CREATE VIEW VENDAS_POR_TAMANHO AS
SELECT 
P.TAMANHO, 
YEAR(N.DATA_VENDA) AS [Ano], 
SUM(I.QUANTIDADE) AS [Venda por Ano]
FROM TABELA_DE_PRODUTOS P
INNER JOIN ITENS_NOTAS_FISCAIS I
ON P.CODIGO_DO_PRODUTO = I.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS N
ON I.NUMERO = N.NUMERO
WHERE YEAR(N.DATA_VENDA) = 2015
GROUP BY P.TAMANHO, YEAR(N.DATA_VENDA)


CREATE VIEW VENDAS_ANO AS
SELECT 
YEAR(N.DATA_VENDA) AS ANO,
SUM(I.QUANTIDADE) AS VENDA
FROM NOTAS_FISCAIS N
INNER JOIN ITENS_NOTAS_FISCAIS I
ON N.NUMERO = I.NUMERO
WHERE YEAR(N.DATA_VENDA) = 2015
GROUP BY YEAR(N.DATA_VENDA)


SELECT 
VT.TAMANHO, VT.Ano, 
VT.[Venda por Ano], 
ROUND((convert(FLOAT, VT.[Venda por Ano]) / convert(FLOAT, VA.VENDA)) * 100, 2) AS Percentual

FROM VENDAS_POR_TAMANHO VT
INNER JOIN VENDAS_ANO VA
ON VT.Ano = VA.ANO
ORDER BY VT.[Venda por Ano] DESC



