SELECT 
N.CPF,
CONVERT(VARCHAR(7), N.DATA_VENDA) AS DATA, 
SUM(I.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS N
INNER JOIN ITENS_NOTAS_FISCAIS I
ON N.NUMERO = I.NUMERO
GROUP BY 
N.CPF,
CONVERT(VARCHAR(7), N.DATA_VENDA)

CREATE VIEW QUERY_INICIAL
AS
SELECT 
N.CPF,
CONVERT(VARCHAR(7), N.DATA_VENDA) AS DATA, 
SUM(I.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS N
INNER JOIN ITENS_NOTAS_FISCAIS I
ON N.NUMERO = I.NUMERO
GROUP BY 
N.CPF,
CONVERT(VARCHAR(7), N.DATA_VENDA)


SELECT CPF, NOME, VOLUME_DE_COMPRA
FROM TABELA_DE_CLIENTES

CREATE VIEW FILTRO
AS
SELECT 
C.CPF as Cpf, 
C.NOME as Nome, 
Q.DATA as Data, 
C.VOLUME_DE_COMPRA AS Volume, 
Q.QUANTIDADE_TOTAL AS [Quantidade Total],
(CASE WHEN C.VOLUME_DE_COMPRA >= Q.QUANTIDADE_TOTAL THEN 'Vendas válidas' ELSE 'Vendas Inválidas' END) AS Resultado
FROM TABELA_DE_CLIENTES C
INNER JOIN QUERY_INICIAL Q
ON C.CPF = Q.CPF
WHERE Q.DATA = '2015-01'

SELECT *, ROUND((1 - (F.Volume/F.[Quantidade Total])) * 100, 2) AS Diferenca
FROM FILTRO F
WHERE F.Volume < F.[Quantidade Total]