SELECT DISTINCT
C.CPF AS CPF, C.NOME AS NOME_CLIENTE, N .CPF
FROM TABELA_DE_CLIENTES C
INNER JOIN
NOTAS_FISCAIS N
ON C.CPF =  N.CPF

SELECT COUNT(*) FROM TABELA_DE_CLIENTES

INSERT INTO TABELA_DE_CLIENTES
(CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, GENERO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA)
VALUES ('09300826320', 'Thalles', 'Nova', '', 'Paz', 'Itabuna', 'RN', '2340000',
'2001-12-12', 22, 'm', 180000, 24500, 0);

SELECT DISTINCT
C.CPF AS CPF, C.NOME AS NOME_CLIENTE, N .CPF
FROM TABELA_DE_CLIENTES C
LEFT JOIN
NOTAS_FISCAIS N
ON C.CPF =  N.CPF
WHERE N.CPF IS NULL