SELECT COUNT(*) FROM TABELA_DE_CLIENTES
 -- 16 CLIENTES

 SELECT COUNT(*) FROM TABELA_DE_VENDEDORES


 SELECT DISTINCT
 VENDEDORES.BAIRRO AS BAIRRO,
 VENDEDORES.NOME AS [NOME DO VENDEDOR],
 CLIENTES.NOME AS [NOME DO CLIENTE]
 FROM TABELA_DE_VENDEDORES VENDEDORES
 INNER JOIN TABELA_DE_CLIENTES CLIENTES
 ON VENDEDORES.BAIRRO = CLIENTES.BAIRRO


SELECT DISTINCT
VENDEDORES.NOME AS [NOME DO VENDEDOR],
VENDEDORES.BAIRRO AS BAIRRO,
CLIENTES.NOME AS [NOME DO CLIENTE]
FROM TABELA_DE_VENDEDORES VENDEDORES
LEFT JOIN TABELA_DE_CLIENTES CLIENTES
ON VENDEDORES.BAIRRO = CLIENTES.BAIRRO
WHERE CLIENTES.NOME IS NULL

SELECT DISTINCT
VENDEDORES.NOME AS [NOME DO VENDEDOR],
VENDEDORES.BAIRRO AS BAIRRO,
CLIENTES.NOME AS [NOME DO CLIENTE]
FROM TABELA_DE_VENDEDORES VENDEDORES
RIGHT JOIN TABELA_DE_CLIENTES CLIENTES
ON VENDEDORES.BAIRRO = CLIENTES.BAIRRO
WHERE VENDEDORES.NOME IS NULL

SELECT DISTINCT
VENDEDORES.NOME AS [NOME DO VENDEDOR],
VENDEDORES.BAIRRO AS BAIRRO,
CLIENTES.NOME AS [NOME DO CLIENTE]
FROM TABELA_DE_VENDEDORES VENDEDORES
FULL JOIN TABELA_DE_CLIENTES CLIENTES
ON VENDEDORES.BAIRRO = CLIENTES.BAIRRO